spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  level:
    root: warn
    com.tracy.demo.generator.sys.mapper: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  #mapper-locations:
    #- com/tracy/demo/mapper/*
